### ISSUE TITLE
Fundir os módulos attach_message e mail da nova API

### ISSUE THREAD

**Issue by alexandrecorreia** [ComunidadeExpresso/expressolivre#13]
Os diretórios trunk/prototype/modules/attach_message e trunk/prototype/modules/mail contém arquivos do mesmo módulo e podem ser fundidos no módulo mail (que tem recebido as funcionalidades desenvolvidas para o expressoMail utilizando a nova API).

OBS.: verificar a possível necessidade de fazer o mesmo com o diretório trunk/prototype/modules/filters.

**Comment by eduardoaprognus** [comment]
Dado a grande diferença entre as estruturas dos diretórios dos módulos supracitados torna-se inviável o esforço de unificar os códigos neste momento.
