### ISSUE TITLE
Adicionar lembrete em evento já criado está com label incorreta

### ISSUE THREAD

**Issue by douglas-lg** [ComunidadeExpresso/expressolivre#45]
Ao adicionar lembrete em um evento já criado, o label está sendo exibido incorretamente, conforme anexo.

![buglembreteevento](https://f.cloud.github.com/assets/6012752/2087299/652cef74-8e69-11e3-9851-c155e5cffab8.png)

**Comment by mauricioviani** [comment]
Este commit é conclusivo? Podemos fechar a Issue?

**Comment by eduardoaprognus** [comment]
Sim, pode ser encerrado.
