### ISSUE TITLE
Impossibilidade de configuração de filtro de mensagens

### ISSUE THREAD

**Issue by douglas-lg** [ComunidadeExpresso/expressolivre#59]
Foi observado a ocorrência da impossibilidade de configuração de filtro de mensagens (do Sieve) para filtros migrados de versões anteriores do Expresso. Ou seja, os filtros das versões antigas do Expresso são identificados e funcionais, porém quando o usuário deseja altera ou criar uma nova regra, nada acontece.

**Comment by xeninhu** [comment]
O commit resolveu o problema escrito na issue? Digo isso pois ele aparentemente resolve apenas problemas de mensagens que possuem acentuação. 

Quanto ao problema descrito da issue, tivemos o mesmo problema aqui na PRODEB, porém apenas quando o usuário possuia muitas regras. Isso acontecia pois a nova abordagem de criação de filtros salvando as regras diretamente em json tornava os scripts até 60% maiores, o que estourava a diretiva sieve_maxscriptsize que por padrão é 32. Aumentamos para 80 e o problema deixou de acontecer.
