### ISSUE TITLE
Inconsistência ao carregar o módulo ContactCenter em determinadas árvores Ldap

### ISSUE THREAD

**Issue by douglas-lg** [ComunidadeExpresso/expressolivre#69]
Foi verificado a ocorrência de inconsistência no módulo ContactCenter quando carregado sobre determinadas configurações de árvores Ldap no Expresso. Em alguns momentos são carregados os contatos vindos do Ldap, em outros momentos não é mais carregado, sendo necessário ao usuário sair e logar novamente no Expresso.

**Comment by cristianocorrea** [comment]
Foi verificado que existe uma preferência que trata deste problema, sendo asssim, não é necessário correção ou adequação no código do ContactCenter.
