### ISSUE TITLE
Marcadores não estão sendo salvos

### ISSUE THREAD

**Issue by filipemotta** [ComunidadeExpresso/expressolivre#92]
Os marcadores do expresso não estão sendo salvos na versão 2.5.2 rc1. 

Quando se cria um marcador, ele aparece na pasta de acompanhamento, porém, ao atualizar a página o marcador desaparece

**Comment by eduardoaprognus** [comment]
Olá, fizemos alguns testes em nosso ambiente e o problema não ocorre. Confira novamente suas configurações de ambiente. 

Caso persista o problema, reporte a versão do navegador e o passo a passo que esta gerando o problema.

**Comment by filipemotta** [comment]
Apos as configurações recomendadas  os problemas com os marcadores nao ocorreram mais...

Obrigado
