### ISSUE TITLE
Problema ao criar marcador 

### ISSUE THREAD

**Issue by filipemotta** [ComunidadeExpresso/expressolivre#93]
Ao selecionar uma mensagem e optar por criar um novo marcador, o expresso abre uma caixa chamada "Configuração do Marcador"

Ao optar por criar um marcador com a opção do lado esquerdo com a opção "+" dos "Meus marcadores" selecionando assim uma cor qualquer o expresso exibe uma mensagem:
"Não foi possível criar o marcador"

Versão RC1 2.5.2

**Comment by eduardoaprognus** [comment]
Este problema não foi constatado em nosso ambiente de testes. A única observação é que ao clicar na opção '+' o marcador é criado com as cores padrão (preto), porém o mesmo é criado.

**Comment by filipemotta** [comment]
Antes de clicar em "Criar",  muda a cor e clica em "Salvar"

**Comment by eduardoaprognus** [comment]
Peço que envie o log do php e do banco de dados, seguindo a ordem das ações até o momento em que o problema ocorrer.

Envie em anexo para o email suporte@prognus.com.br, assim poderemos analisar melhor o problema.

**Comment by eduardoaprognus** [comment]
Antes de enviar os logs, peço que verifique e configure os arquivos conforme o seu ambiente localizados no diretório 'prototype/config':

Cyrus.srv;
OpenLDAP.srv;
PostgreSQL.srv

**Comment by filipemotta** [comment]
Certo Eduardo,

Realmente essa etapa nao fiz, mas so poderei fazer amanha e te dou uma posição

**Comment by eduardoaprognus** [comment]
Filipe, lembrando também que é necessário seguir todo o procedimento de atualizações presentes no trac:

A partir da versão 2.2.x
1. Veja a instalação/configuração da versão 2.4.0: http://trac.expressolivre.org/wiki/versoes/24#Apartirdavers%C3%A3o2.2.x
2. Veja a instalação/configuração da versão 2.4.1:
   http://trac.expressolivre.org/wiki/versoes/241#Apartirdavers%C3%A3o2.2.x

**Comment by filipemotta** [comment]
Eduardo,

Apos as configurações os problemas com os marcadores nao ocorreram mais...

Obrigado
