### ISSUE TITLE
Problema ao responder/encaminhar mensagens pelo dispositivo móvel

### ISSUE THREAD

**Issue by eduardoaprognus** [ComunidadeExpresso/expressolivre#95]
Ao responder/encaminhar uma mensagem pelo dispositivo móvel (z-push), as flags não são marcadas no IMAP e consequentemente não são mostradas no módulo expressoMail ou mesmo pelo z-push.

**Comment by cristianocorrea** [comment]
Solved >> https://github.com/ComunidadeExpresso/expressolivre/commit/a2ffc55ffe51067d56e08327b56a91d26aa24010

**Comment by cristianocorrea** [comment]
Atualizado o modulo z-push para revisão 2.1.2.
