### ISSUE TITLE
Atualização do Expresso e módulos para a versão 2.5.2

### ISSUE THREAD

**Issue by douglas-lg** [ComunidadeExpresso/expressolivre#97]
Implementar a atualização do Expresso e seus módulos, da versão 2.5.1.0 para a versão 2.5.2.

**Comment by cristianocorrea** [comment]
Atualizado os módulos para versão 2.5.2.
Efetuada optimização das queries de log, conforme sugestão do colaborador "Marcio Moriaki Ishikawa" via e-mail;
