### ISSUE TITLE
mensagem errada ao pesquisar mensagens

### ISSUE THREAD

**Issue by filipemotta** [ComunidadeExpresso/expressolivre#99]
Ao pesquisar conteudo das mensagens no modulo expresso mail ( item da primeira opção com uma lupa ) o expresso apresenta a seguinte mensagem:

"Pesquisando Mensagens da pasta atual Cancelar"

Idenpendente da pasta  pesquisada.

Ao meu ver, a opção "Cancelar" deveria estar separada da mensagem 

![bug](https://cloud.githubusercontent.com/assets/2566082/3287780/88b38b60-f55c-11e3-9c43-07b38e6dc93d.png)

**Comment by eduardoaprognus** [comment]
Correções:

Master: https://github.com/ComunidadeExpresso/expressolivre/commit/89896a9032b8372c9c64d1a908516ff3aaa842e1

Branch 2.5.2: https://github.com/ComunidadeExpresso/expressolivre/commit/e2c47ba3d8ceff019c5a2142238f3a198e5240b4
